/**
 * Card front/back text is authored by the user, generated by an AI provider, or
 * carried in from an Anki deck, and it is rendered with `dangerouslySetInnerHTML`
 * so the lightweight formatting below can apply. Escaping therefore has to run
 * before any markup is introduced, and it has to live in exactly one place —
 * two copies of an escaping routine is two chances for them to drift apart.
 */
export function escapeHtml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

/**
 * Renders the small formatting vocabulary Pupil supports on a card face:
 * `**bold**`, `*italic*`, `` `code` ``, `_____` for a cloze blank, and newlines.
 *
 * Every replacement runs against already-escaped text, so a card containing
 * `<script>` yields inert markup rather than an element.
 */
export function renderCardMarkup(value: string, clozeClassName: string): string {
  return escapeHtml(value)
    .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
    .replace(/\*(.+?)\*/g, "<em>$1</em>")
    .replace(/`(.+?)`/g, "<code>$1</code>")
    .replace(/_____/g, `<span class="${clozeClassName}"></span>`)
    .replace(/\n/g, "<br>");
}
